"""init

Revision ID: 846f921fd198
Revises: 
Create Date: 2026-05-28 15:15:25.289636

"""
from alembic import op
import sqlalchemy as sa


revision = '846f921fd198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.Column('ogrn', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=120), nullable=True),
    sa.Column('legal_address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('okved_codes', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('avg_response_time_hours', sa.Integer(), nullable=True),
    sa.Column('historical_score', sa.Float(), nullable=True),
    sa.Column('spark_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_inn'), 'suppliers', ['inn'], unique=True)
    op.create_table('historical_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('nsi_sku', sa.String(length=80), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('price_rub', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('purchase_date', sa.String(length=20), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_purchases_nsi_sku'), 'historical_purchases', ['nsi_sku'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('raw_request', sa.Text(), nullable=False),
    sa.Column('phase', sa.Enum('pre_nmck', 'post_tender_published', 'unregulated', name='procurementphase'), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('draft', 'planned', 'sourcing', 'rfq_sent', 'responses_collected', 'negotiating', 'verified', 'report_ready', 'approved', 'rejected', 'escalated', 'failed', name='lotstatus'), nullable=False),
    sa.Column('total_estimated_rub', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nmck_rub', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('parsed_items', sa.JSON(), nullable=True),
    sa.Column('chosen_supplier_id', sa.String(length=36), nullable=True),
    sa.Column('final_report', sa.JSON(), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_created_at'), 'lots', ['created_at'], unique=False)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_table('nsi_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('gost', sa.String(length=80), nullable=True),
    sa.Column('typical_price_rub', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('embedding_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nsi_items_category'), 'nsi_items', ['category'], unique=False)
    op.create_index(op.f('ix_nsi_items_sku'), 'nsi_items', ['sku'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=40), nullable=False),
    sa.Column('step_name', sa.String(length=80), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('llm_response_raw', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_agent_name'), 'audit_log', ['agent_name'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_lot_id'), 'audit_log', ['lot_id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('initial_offer', sa.JSON(), nullable=True),
    sa.Column('target_discount_pct', sa.Float(), nullable=True),
    sa.Column('final_offer', sa.JSON(), nullable=True),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('allowed_by_filter', sa.Boolean(), nullable=False),
    sa.Column('filter_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfq_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('references_ids', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_offer', sa.JSON(), nullable=True),
    sa.Column('raw_email_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_emails_lot_id'), 'rfq_emails', ['lot_id'], unique=False)
    op.create_index(op.f('ix_rfq_emails_message_id'), 'rfq_emails', ['message_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('inn_valid', sa.Boolean(), nullable=True),
    sa.Column('ogrn_valid', sa.Boolean(), nullable=True),
    sa.Column('spark_match', sa.Boolean(), nullable=True),
    sa.Column('price_consistent', sa.Boolean(), nullable=True),
    sa.Column('lead_time_meets_spec', sa.Boolean(), nullable=True),
    sa.Column('gost_match', sa.Boolean(), nullable=True),
    sa.Column('discrepancies', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verifier_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_index(op.f('ix_rfq_emails_message_id'), table_name='rfq_emails')
    op.drop_index(op.f('ix_rfq_emails_lot_id'), table_name='rfq_emails')
    op.drop_table('rfq_emails')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_audit_log_lot_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_agent_name'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_nsi_items_sku'), table_name='nsi_items')
    op.drop_index(op.f('ix_nsi_items_category'), table_name='nsi_items')
    op.drop_table('nsi_items')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_created_at'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_historical_purchases_nsi_sku'), table_name='historical_purchases')
    op.drop_table('historical_purchases')
    op.drop_index(op.f('ix_suppliers_inn'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('customers')
    # ### end Alembic commands ###
