apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: snabagent
    component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    app: snabagent
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: snabagent
    component: ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
  selector:
    app: snabagent
    component: ui
